# Generated by Django 5.2.2 on 2025-06-30 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_post_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='author',
            field=models.CharField(default='<UNK>', max_length=100),
        ),
    ]
