# Generated by Django 5.2.2 on 2025-07-05 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_comment_dislike_comment_like_comment_parent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='post_id',
            new_name='post',
        ),
    ]
